name: .NET

on:
  push:

jobs:

  run-unit-tests:
    runs-on: windows-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore nuget packages
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run unit tests
      run: dotnet test --no-build
