# This workflow is responsible for:
# -Downloading source code from repository
# -Setting up .NET & Restoring nugets & building solution
# -Running unit tests

# Workflow name
name: .NET

# Workflow trigger condition
on:
  push:

# List of jobs to be done in this workflow
jobs:
  run-ui-tests:
    runs-on: windows-latest

    steps:
      # Clone repository
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # Install .NET Core
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      # Restore nuget packages defined in solution
      - name: Restore nuget packages
        run: dotnet restore

      # Build solution
      - name: Build
        run: dotnet build --no-restore

      # Publish project to create artifacts
      - name: Publish
        run: dotnet publish GithubPipelinesLearning/GithubPipelinesLearning.csproj -c Release -o release --nologo

      # Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.ref_name }}-artifacts
          path: ${{ github.workspace }}\releases\
          if-no-files-found: error
