# Workflow name
name: workflow_call_1

# Workflow trigger condition
on:
  workflow_call:

# After pushing new commit, previous jobs will be cancelled
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# List of jobs to be done in this workflow
jobs:
  run-ui-tests:
    runs-on: self-hosted
    steps:
      # Clone repository
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # Install .NET Core
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      # Restore nuget packages defined in solution asdasdasd
      - name: Restore nuget packages
        run: dotnet restore

      # Build solution
      - name: Build
        run: dotnet build --no-restore

      # Run unit tests defined in solutionasdasd
      - name: Run Ui tests
        run: dotnet test GithubPipelinesLearning.UiTests2\bin\Debug\net6.0\GithubPipelinesLearning.UiTests2.dll --no-build
