# Workflow name
name: workflow_call_1

# Workflow trigger condition
on:
  workflow_call:

# List of jobs to be done in this workflow
jobs:
  run-unit-tests:
    runs-on: windows-latest
    steps:
      # Clone repository
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # Install .NET Core
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      # Restore nuget packages defined in solution
      - name: Restore nuget packages
        run: dotnet restore

      # Build solution
      - name: Build
        run: dotnet build --no-restore

      # Run unit tests defined in solution
      - name: Run unit tests
        run: dotnet test GithubPipelinesLearning.UnitTests\bin\Debug\net6.0\GithubPipelinesLearning.UnitTests.dll --no-build
